### ISSUE TITLE
Plasma: Initial issues

### ISSUE THREAD

**Issue by ReillyBrogan** [serpent-os/recipes#952]
Please post any initial issues with Plasma session/SDDM here and I'll fix them as I can.

Instructions for installing Plasma:
```
sudo moss ur
sudo moss it pkgset-aeryn-plasma-recommended branding-aeryn-plasma
```

Instructions for switching to SDDM:
```
sudo moss ur
sudo moss rm gdm
sudo moss it sddm
```

Instructions for switching to plasma-login-manager (NOTE: Very experimental and not supported):
```
sudo moss ur
sudo moss rm gdm
sudo moss it plasma-login-manager
```

**Comment by ReillyBrogan** [comment]
> When the PC starts up and the user logs in, the Wi-Fi does not connect automatically, even though it did before. There is no need to re-enter the Wi-Fi key; you just need to manually tell Plasma to connect to the Wi-Fi after logging in.
> 
> Login manager : plasma-login-manager Plasma version : 6.4.3

Journal logs please. Probably something pam or kwallet related. 

And this doesn't happen in gnome? What about when using sddm?

**Comment by HarshRelapse** [comment]
Thanks for the sync! I've noticed another issue, this time with the media control in Firefox's private windows:

1. The Plasma Integration media control (addon) doesn't work in private windows because it lacks permission to run in private windows.
2. Firefox's built-in media control does work in private windows, but it should be turned off according to [KDE's recommendations](https://community.kde.org/Distributions/Packaging_Recommendations#Firefox_configuration).

When I use YouTube or SoundCloud in private windows, I rely on a toggle to stop or start media. This means I can't stop media from private tabs using Plasma's media control, even though Firefox's media control is functional.

To resolve this issue, there are 2 solutions:

1. Turn off Firefox's media controls (to follow upstream recommendations) and allow Plasma Integration to work in private windows by granting the add-on permission.
2. Keep Firefox's media controls enabled and disable the controls from Plasma Integration.

**Comment by KwisatzJim** [comment]
the Users section of Plasma Settings is blank, doesn't show the user created during AerynOS install.

**Comment by ReillyBrogan** [comment]
> The xdg-user-dirs package isn't installed by default in a lichen installed plasma environment, so the user directory only contains the workspace folder. When installing a package like steam that has xdg-user-dirs as a dependency, restarting the system causes all the user folders to be created. However, these folders are not pinned to the sidebar of dolphin.
> 
> Edit 1: plasma-desktop has "binary(xdg-user-dir)" as dependency, but It is not installed in the fresh plasma system.

Fixed by bf8652d6347a788b73903e439765e05aef4e4737. It was added as a builddep but not a rundep.

**Comment by HarshRelapse** [comment]
Currently on volatile: 
Firefox 143.0
plasma 6.4.5

Media controls are broken. The keyboard shortcuts aren't working anymore, and the taskbar doesn't display the media start/stop icon. Previously, the media shortcuts worked (Firefox off; KDE on), but now only enabling the media control in Firefox (kde off or on doesn't matter anymore) resolves this issue. Could be a regression since it worked before?

**Comment by HarshRelapse** [comment]
The plasma integration is still active (with media control in sub-settings), even a disable/enable doesn't fix it. For some reason kde media control needs Firefox media control enabled?

**Comment by HarshRelapse** [comment]
I do not know how nit picky I should be with the issues, so I am just gonna leave it here.

<img width="1062" height="809" alt="Image" src="https://github.com/user-attachments/assets/5aae7695-8c64-4916-8eba-fa0d106c7a75" />

**Comment by ReillyBrogan** [comment]
> I do not know how nit picky I should be with the issues, so I am just gonna leave it here.
> <img alt="Image" width="1062" height="809" src="https://private-user-images.githubusercontent.com/229744164/491897121-5aae7695-8c64-4916-8eba-fa0d106c7a75.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTgzOTQ4NDksIm5iZiI6MTc1ODM5NDU0OSwicGF0aCI6Ii8yMjk3NDQxNjQvNDkxODk3MTIxLTVhYWU3Njk1LThjNjQtNDkxNi04ZWJhLWZhMGQxMDZjN2E3NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwOTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDkyMFQxODU1NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01OWM0MDI5ZjZmMWMyOGZjMTQ0YjJlZGM5YmNmNTFlMDllMmI1YjRiZWQzYmVhZWMwYTU2ZTgzNTJkYWM5MjQ0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.tm0SjJzbtyZlTHOK-4sQpTwd5UQm3Hb4Prqma4fZaPA">

Yeah I know about that one. We don't package the xdpyinfo tool on Aeryn currently which is used to get information about the running xserver. Obviously we don't support X11 sessions so that part isn't particularly useful. I think it still can be used to get information from xwayland but I'm not sure if it's worth packaging it just for that reason.
